### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by pegases** [ffplayout/messenger#1]
can you help me create installation documentation thank you

**Comment by jb-alvarado** [comment]
one which step exactly you need help? In which environment do you want to run this?

**Comment by pegases** [comment]
I install ffplayout engine and mistletoe it works well I would like to install messeger on a linux debian, I install the server but I do not understand how to install the client and access it, thank you for your help

 

De : jb-alvarado <notifications@github.com> 
Envoyé : samedi 21 mars 2020 16:50
À : ffplayout/messenger <messenger@noreply.github.com>
Cc : PEGASES <denis@pegases.net>; Author <author@noreply.github.com>
Objet : Re: [ffplayout/messenger] installation (#1)

 

one which step exactly you need help? In which environment do you want to run this?

**Comment by jb-alvarado** [comment]
For the client you just install the dependencies, edit the ini file in asset folder and run the `messenger.pyw`. When you are on a linux desktop, you need check if you can execute scripts directly from file browser. From command line you can always run the script.

Here are step by step:
1. cd into client folder
2. edit `assets/messenger.ini`
3. install dependencies: `pip install -r requirements-base.txt`
4. run in `./messenger.pyw`

**Comment by pegases** [comment]
THANK YOU FOR YOUR HELP

 

De : jb-alvarado <notifications@github.com> 
Envoyé : dimanche 22 mars 2020 08:06
À : ffplayout/messenger <messenger@noreply.github.com>
Cc : PEGASES <denis@pegases.net>; Author <author@noreply.github.com>
Objet : Re: [ffplayout/messenger] installation (#1)

 

For the client you just install the dependencies, edit the ini file in asset folder and run the messenger.pyw. When you are on a linux desktop, you need check if you can execute scripts directly from file browser. From command line you can always run the script.

Here are step by step:

1.	cd into client folder
2.	edit assets/messenger.ini
3.	install dependencies: pip install -r requirements-base.txt
4.	run in ./messenger.pyw
